seo:
  site_name: Example
  title: Example SEO Title
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_url:
  facebook_url:
  pinterest_url:
  linkedin_url:
design:
  dark-text_color: '#3c3c41'
  medium-text_color: '#5a5a5f'
  light-text_color: '#f7f5f3'
  featured-text_color: '#ff0000'
  dark_color: '#6B78A5'
  medium_color: '#C8AA64'
  light_color: '#EBD8AB'
  v-light_color: '#9CA6CB'
  featured_color: '#B6CEA6'
  accent_color: '#a74a4a'
